### ISSUE TITLE
login button greyed out

### ISSUE THREAD

**Issue by kevinmarks** [dissolve/mobilepub#1]
(On Nexus 6, Lollipop) entering the URL http://known.kevinmarks.com doesn't let me click login

**Comment by kevinmarks** [comment]
```
    <button id="login-btn" class="online-only"{{#unless isOnline}} disabled="disabled" {{/unless}}>Login</button>
    {{#unless isOnline}}<div class="offline-only-view">Login Require Internet Access.</div>{{/unless}}
```

looks like this is failing and assuming I'm offline as "Login Require Internet Access" is shown

**Comment by dissolve** [comment]
It appears the login on graying out this data is backwards, not sure how i missed it.  I suspect on versions prior to Lollipop it wasn't triggering the event correctly.
