### ISSUE TITLE
Support for Syndication Targets via q=syndicate-to

### ISSUE THREAD

**Issue by miklb** [dissolve/mobilepub#17]
As started in 2254d635db9d58405456b55c57a403b2c8d42f39, support the q=syndicate-to per the [Micropub spec](https://www.w3.org/TR/2016/CR-micropub-20160816/#syndication-targets).

Granted, I'm not 100% sure *how* that differs from current implementations. Thanks for the considerations and I look forward to testing more.

**Comment by dissolve** [comment]
Code to fix this has been pushed to the live site.  Can verify you are using the new version of the code when the settings page shows version information at the bottom.

**Comment by miklb** [comment]
Just tested, and see version 1.1.4 on settings page and a button to force refresh Syndication Targets. However I'm still confused on how that is supposed to work. Not seeing options on the publish note page. Appreciate the work thus far on this.

**Comment by dissolve** [comment]
When you force refresh, is it getting a bulleted list of your endpoints?
You should see a multiselect field as the last item on the create page with those options.

Its expecting json only, and they have to have 'uid' and 'name' set (like https://www.w3.org/TR/micropub/#syndication-targets )
or they won't show up at all.

Here are samples of what it looks like for me.

https://ben.thatmustbe.me/upload/files/117_inkstone-post.png
https://ben.thatmustbe.me/upload/files/118_inkstone-settings.png

**Comment by miklb** [comment]
Determined issue was with the micropub  endpoint I was using was sending `application/x-www-form-urlencoded`. [Issue was opened](https://github.com/voxpelli/node-micropub-express/issues/5) to change behavior to send `application/json`, however has been fixed in Inkstone. 

Closing as resolved. Thanks again for the help debugging.

**Comment by dissolve** [comment]
to be clear, inkstone was not requesting application/json specifically.  this has been fixed as of v 1.1.6
