### ISSUE TITLE
Depends on the authorization endpoint returning a me parameter.

### ISSUE THREAD

**Issue by Zegnat** [dissolve/mobilepub#18]
> There seems to have been an issue in the login process. Data needed to verify your login is missing.

The authorization endpoint of Sink was built according to [the IndieAuth spec](https://indieauth.net/spec/), so it does not send a `me` parameter to the `redirect_uri`. (See [5.3 Authorization Response](https://indieauth.net/spec/#authorization-response).) Looking for the error message in InkStone’s source, [it looks like](https://github.com/Inklings-io/inkstone/blob/780c1a7f9206f30600b66e54b7a3e0fc3aafb3d4/src/login.js#L20) InkStone requires the `me` parameter.

**Comment by dissolve** [comment]
fixed in 1.1.10
