### ISSUE TITLE
Invalid client_id

### ISSUE THREAD

**Issue by edjw** [dissolve/mobilepub#3]
Indieauth gives an Invalid client_id error when I try to log in using my domain. "The client_id must be a valid URL. The client_id provided was: MobilePub"

I'm using my own domain which is linked to a hosted Known site.

**Comment by cweiske** [comment]
`client_id` MUST be a full URI, see the spec at https://indiewebcamp.com/IndieAuthProtocol#Request:

> client_id
>    Full URI of the application's/website's home page. Used to identify the application. An authorization endpoint may show the application's icon and title to the user during the auth process.

**Comment by dissolve** [comment]
closing all existing issues given the rewrite.  It is giving a domain in the new version.
